services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: nodestack_dev
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    build: .
    ports:
      - 5001:5001
      - 9229:9229 # for debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/nodestack_dev
      PORT: 5001
