services:
  backend:
    build: .
    ports:
      - 5001:5001
      - 9229:9229 # for debugging
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    environment:
      PORT: 5001